#!/usr/bin/env sh
# Prints details of the currently running event

set -e

start_time=$(date '+%H:%M')
end_time=$(date -d '+1 hour' '+%H:%M')

output=$(
  gcalcli agenda "$start_time" "$end_time" \
    --tsv \
    --config-folder "$XDG_CONFIG_HOME/gcalcli/" |
    head -n 1
)

event_start_time=$(echo "$output" | awk -F'\t' '{ print $2 }')
event_end_time=$(echo "$output" | awk -F'\t' '{ print $4 }')
event_name=$(echo "$output" | awk -F'\t' '{ print $5 }')

# Assuming they're on the same day
printf '%s (%s-%s)\n' "$event_name" "$event_start_time" "$event_end_time"
