#!/usr/bin/env sh
# Prints details of the currently running event, or next upcoming event today.

set -e

GCALCLI_AGENDA="gcalcli agenda --config-folder=$XDG_CONFIG_HOME/gcalcli/ --tsv"

start_time=$(date -d '+10 minutes' '+%H:%M')
end_time=$(date -d '+70 minutes' '+%H:%M')

output=$($GCALCLI_AGENDA "$start_time" "$end_time" | head -n 1)

# If empty output, then no current event
if [ -z "$output" ]; then
  output=$($GCALCLI_AGENDA --nostarted | head -n 1)

  event_date=$(echo "$output" | awk -F'\t' '{ print $1 }')
  curr_date=$(date '+%Y-%m-%d')

  if [ "$event_date" = "$curr_date" ]; then
    event_start_time=$(echo "$output" | awk -F'\t' '{ print $2 }')
    event_end_time=$(echo "$output" | awk -F'\t' '{ print $4 }')
    event_name=$(echo "$output" | awk -F'\t' '{ print $5 }')
    printf 'Free until %s (%s)\n' "$event_start_time" "$event_name"
  fi
  exit 0
fi

event_start_time=$(echo "$output" | awk -F'\t' '{ print $2 }')
event_end_time=$(echo "$output" | awk -F'\t' '{ print $4 }')
event_name=$(echo "$output" | awk -F'\t' '{ print $5 }')

# Assuming they're on the same day
printf '%s (%s-%s)\n' "$event_name" "$event_start_time" "$event_end_time"
