#!/usr/bin/env bash
# Prints currently playing song on Spotify
# Requires playerctl

shorten() {
  awk -v len=30 '{ if (length($0) > len) print substr($0, 1, len-3) ".."; else print; }'
}

[ "$(playerctl --player=spotify status)" = "Playing" ] &&
  echo "🎶 $(playerctl metadata album | shorten): $(playerctl metadata title)" |
  sed 's/\&/\&amp;/g' ||
  echo ''
