#!/usr/bin/env bash
# Prints currently playing song on Spotify
# Requires playerctl

trunc() {
  awk -v len=$1 '{ if (length($0) > len) print substr($0, 1, len-3) ".."; else print; }'
}

album=$(playerctl metadata album | trunc 30)
title=$(playerctl metadata title | trunc 40)

[ "$(playerctl --player=spotify status)" = "Playing" ] &&
  echo "🎶 $album: $title" | sed 's/\&/\&amp;/g' ||
  echo ''
