#!/bin/sh
# Prints the volume percentage with a speaker emoji

# Outputs something like: "Front Right: Playback 29113 44% off"
volinfo=$(amixer -D pulse sget Master | tail -n 1 | sed 's/\[//g; s/\]//g')

if [ -z "$volinfo" ]; then
  echo "❌ ERR"
else
  if [ "$(echo $volinfo | awk '{print $6}')" = "off" ]; then
    echo "🔇 MUTE"
  else
    # Volume percentage (excl. % sign)
    vol=$(echo $volinfo | awk '{print $5}' | sed 's/.$//')

    case "$vol" in
      0) emoji="🔇" ;;
      [1-9] | [1-2][0-9]) emoji="🔈" ;;
      [3-6][0-9]) emoji="🔉" ;;
      [7-9][0-9] | 100) emoji="🔊" ;;
      *) emoji="❌" ;;
    esac

    echo "$emoji $vol%"
  fi
fi
