defaultIndent: "  "
removeTrailingWhitespace: 1

indentAfterItems:
    itemize: 0
    enumerate: 0
    description: 0
    list: 0

modifyLineBreaks:
  preserveBlankLines: 0
  condenseMultipleBlankLinesInto: 1

  textWrapOptions:
    columns: 0
