defaultIndent: "  "
removeTrailingWhitespace: 1

indentAfterItems:
  itemize: 1
  enumerate: 1
  description: 1
  list: 1

modifyLineBreaks:
  preserveBlankLines: 0
  condenseMultipleBlankLinesInto: 1

  textWrapOptions:
    columns: 80
    items: 1
  removeParagraphLineBreaks:
    beforeTextWrap: 1
